CREATE DATABASE CONFERENCE_REVIEW;
SHOW DATABASES;
USE CONFERENCE_REVIEW;
CREATE TABLE PAPER
(
Id INTEGER unsigned NOT NULL AUTO_INCREMENT,
Title VARCHAR(150) NOT NULL,
Abstract VARCHAR(2000) NOT NULL,
FileName VARCHAR(300) NOT NULL,
PRIMARY KEY (Id)
);
CREATE TABLE AUTHOR
(
EmailAddr VARCHAR(320) NOT NULL UNIQUE,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(100) NOT NULL,
PRIMARY KEY (EmailAddr)
);
CREATE TABLE TOPIC
(
Id INTEGER unsigned NOT NULL AUTO_INCREMENT,
TopicName VARCHAR(150) NOT NULL,
PRIMARY KEY (Id)
);
CREATE TABLE REVIEWER
(
EmailAddr VARCHAR(320) NOT NULL UNIQUE,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(100) NOT NULL,
AuthorFeedback VARCHAR(2000) NOT NULL,
CommiteeFeedback VARCHAR(2000) NOT NULL,
PhoneNum VARCHAR(15) NOT NULL,
Affiliation VARCHAR(1000) NOT NULL,
PRIMARY KEY (EmailAddr)
);
CREATE TABLE REVIEWER_TOPIC
(
TopicId INTEGER unsigned NOT NULL,
ReviewerId VARCHAR(320) NOT NULL,
FOREIGN KEY (TopicId) REFERENCES TOPIC (Id),
FOREIGN KEY (ReviewerId) REFERENCES REVIEWER (EmailAddr)
);


CREATE TABLE REVIEW
(
Id INTEGER unsigned NOT NULL AUTO_INCREMENT,
Recommendation VARCHAR(300) NOT NULL,
MeritScore INTEGER unsigned NOT NULL,
PaperId INTEGER unsigned NOT NULL,
ReadabilityScore INTEGER unsigned NOT NULL,
ReviewerId VARCHAR(320) NOT NULL,
OriginalityScore INTEGER unsigned NOT NULL,
RelevanceScore INTEGER unsigned NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (PaperId) REFERENCES PAPER(Id),
FOREIGN KEY (ReviewerId) REFERENCES REVIEWER(EmailAddr)
);
CREATE TABLE ASSIGNED
(
PaperId INTEGER unsigned NOT NULL,
ReviewerId VARCHAR(320) NOT NULL,
FOREIGN KEY (PaperId) REFERENCES PAPER(Id),
FOREIGN KEY (ReviewerId) REFERENCES REVIEWER(EmailAddr)
);